services:
  api:
    build: .
    ports: ["3000:3000"]
    volumes:
      - logs_volume:/app/logs
    healthcheck:
      test: ["CMD", "/app/lgr_ehr", "--health"]
      interval: 10s
      timeout: 2s
      retries: 3

volumes:
  logs_volume: