services:
  lgr_ehr:
    build: .
    image: lgr_ehr:dev
    depends_on:
      - db
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RUST_LOG=${RUST_LOG}
    ports: ["3000:3000"]
    volumes:
      - logs_volume:/app/logs
    healthcheck:
      test: ["CMD", "/app/lgr_ehr", "--health"]
      interval: 10s
      timeout: 2s
      retries: 3

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  logs_volume:
  db_data: